version: '3'

services:
    elasticsearch:
        image: elasticsearch:7.6.2
        environment:
            - discovery.type=single-node
            - "ES_JAVA_OPTS=-Xms256m -Xmx256m"
        ports:
            - 9200:9200
        deploy:
            resources:
                limits:
                    memory: 1g
    kibana:
        image: kibana:7.6.2
        ports:
            - 5601:5601
        deploy:
            resources:
                limits:
                    memory: 1g
        depends_on:
            - elasticsearch 
    fluent-bit:
        image: fluent/fluent-bit:1.4.3
        command: /fluent-bit/bin/fluent-bit -c /fluent-bit/config/fluent-bit.conf
        ports:
            - 5170:5170
        volumes:
            - ./fluent-bit.conf:/fluent-bit/config/fluent-bit.conf
        deploy:
            resources:
                limits:
                    memory: 60m
        depends_on:
            - elasticsearch