@startuml
|Frontend|
start
partition "US1: Jane logs into the application" {
    :foo1;
    |#AntiqueWhite|Backend|
    :foo2;
    |#AntiqueWhite|Backend2|
    :foo3;
}

partition "US2: Jane sees the dashboard" {
    |Frontend|
    :foo4;
    |Backend3|
    :foo5;
}
stop
@enduml

