openapi: 3.0.0
info:
  version: 1.0.0
  title: Multi Tenant App
  description: This is a description
tags:
  - name: Account
    description: A collection of APIs for accounts
paths:

  /api/account/create_account:
    post:
      tags:
        - Account
      summary: Create an Account
      operationId: createAccount
      parameters:
        - in: header
          name: tenant_id
          schema:
            type: string
          required: true
      requestBody:
        description: ""
        content:
          application/json:
            schema:
              type: object
              properties:
                account_id: 
                  type: string
                username: 
                  type: string
                password:
                  type: string
      responses:
        200:
          description: ""
          content: 
            application/json:
              schema:
                type: object

  /api/account/get_all_accounts:
    post:
      tags:
        - Account
      summary: Get All Accounts
      operationId: getAllAccounts
      parameters:
        - in: header
          name: tenant_id
          schema:
            type: string
          required: true
      responses:
        200:
          description: ""
          content: 
            application/json:
              schema:
                type: array
                items:
                  type: object
                  properties:
                    account_id:
                      type: string
                    username:
                      type: string